from datetime import datetime
from flask import Blueprint, send_file
from reportlab.pdfgen import canvas
import io

report_bp = Blueprint(
    "report_bp",
    __name__
)

@report_bp.route("/download_report")
def download_report():

    buffer = io.BytesIO()

    pdf = canvas.Canvas(buffer)
    pdf.setFillColorRGB(0.2, 0.4, 0.8)
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(180, 800, "KidoDoc AI Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(100, 750, "Child Name: Aarav")
    pdf.drawString(100, 720, "Predicted Disease: Fungal Infection")
    pdf.drawString(100, 690, "Health Status: Stable")
    pdf.drawString(100, 660, "Generated by KidoDoc AI")
    pdf.drawString(
        100,
        630,
        f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M')}"
)
    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="kidodoc_report.pdf",
        mimetype="application/pdf"
    )